language: csharp
mono:
  - 3.12.1
script:
  - ./build.sh
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/27802a90e2ed8acb2d49
    on_success: change
    on_failure: always
    on_start: false
