language: csharp
mono:
  - 3.12.0
script:
  - ./build.sh
cache:
  directories:
    - $HOME/.dnx
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/27802a90e2ed8acb2d49
    on_success: change
    on_failure: always
    on_start: false
